### ISSUE TITLE
Need ability to add custom tags to OpenTracing Span object during query execution

### ISSUE THREAD

**Issue by RileyJia** [opentracing-contrib/java-cassandra-driver#22]
We want to add custom tags to OpenTracing Span object by overriding/augmenting methods in `TracingSession.java` . This can be accomplished by making `buildSpan()`, `finishSpan()`, and `errorLogs()` methods public so that subclasses can override them and provide custom implemtation.

**Comment by RileyJia** [comment]
Here is the pull request: https://github.com/opentracing-contrib/java-cassandra-driver/pull/23

**Comment by malafeev** [comment]
merged #23 and released new version
