### ISSUE TITLE
Want peer.ipv4 tag to be a string instead of integer

### ISSUE THREAD

**Issue by RileyJia** [opentracing-contrib/java-cassandra-driver#25]
We want to extract IP address from the ipv4 tag. TracingSession is writing the int representation of the ipv4 address which makes the tag representation hard to understand.

**Comment by RileyJia** [comment]
Here is the pull request https://github.com/opentracing-contrib/java-cassandra-driver/pull/26

**Comment by malafeev** [comment]
merged #26 and released
