### ISSUE TITLE
Provide alternative/more informative operation names for spans 

### ISSUE THREAD

**Issue by JordanJLopez** [opentracing-contrib/java-cassandra-driver#6]
My team is currently exploring the use of this driver at HomeAway, and we were hoping to get more options for the operation name of the span. Currently it's hardcoded to "execute" at this [line](https://github.com/opentracing-contrib/java-cassandra-driver/blob/master/src/main/java/io/opentracing/contrib/cassandra/TracingSession.java#L301).

**Comment by JordanJLopez** [comment]
I'm currently creating a pull request that introduces a Span Name Provider interface that would allow users to create their own span name based on the query being executed.

**Comment by JordanJLopez** [comment]
Resolved with https://github.com/opentracing-contrib/java-cassandra-driver/pull/7

**Comment by tedsuo** [comment]
Thanks @JordanJLopez, super helpful.
